<?php
/**
 * @file
 * Responsive Menu Commons
 */

define('RNJS_SITE_URL', 'http://www.meanthemes.com/plugins/meanmenu/');
define('RNJS_GITHUB_URL', 'https://github.com/weare2ndfloor/meanMenu');
define('RNJS_DOWNLOAD_URI', 'https://github.com/weare2ndfloor/meanMenu/archive/master.zip');
define('RNJS_MAIN_JS', 'jquery.meanmenu.js');
define('RNJS_MAIN_JS_MIN', 'jquery.meanmenu.2.0.min.js');
define('RNJS_MAIN_CSS', 'meanmenu.css');
